plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
title: Waifu2x Usage
description: How to use Waifu2x properly and effectively to remove the noise from your images. 

theme: jekyll-theme-slate
